INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Palace", "59", "energiteca59@coexito.com.co", 16);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("La 33", "60", "energiteca60@coexito.com.co", 16);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Itagui", "B8", "energitecaB8@coexito.com.co", 16);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Guayabal", "J8", "energitecaJ8@coexito.com.co", 16);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("San Diego", "P3", "energitecaP3@coexito.com.co", 16);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("La Chimenea", "P6", "energitecaP6@coexito.com.co", 16);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("30 de Agosto", "61", "energiteca61@coexito.com.co", 20);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Armenia", "67", "energiteca67@coexito.com.co", 1);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Manizales", "68", "energiteca68@coexito.com.co", 15);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Belen", "P7", "energitecaP7@coexito.com.co", 15);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Dos Quebradas", "L7", "energitecaL7@coexito.com.co", 10);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Cra. 15/28", "31", "energiteca31@coexito.com.co", 5);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("La Hormiga", "A8", "energitecaA8@coexito.com.co", 5);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("La Rosita", "Z5", "energitecaZ5@coexito.com.co", 5);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Barrancabermeja", "32", "energiteca32@coexito.com.co", 2);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Cucuta", "33", "energiteca33@coexito.com.co", 9);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Gran Colombia", "P5", "energitecaP5@coexito.com.co", 9);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Girardot", "34", "energiteca34@coexito.com.co", 12);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Neiva", "36", "energiteca36@coexito.com.co", 31);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Ibague", "37", "energiteca37@coexito.com.co", 13);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("La Dorada", "55", "energiteca55@coexito.com.co", 14);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Villavicencio", "50", "energiteca50@coexito.com.co", 27);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Yopal", "P9", "energitecaP9@coexito.com.co", 28);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Cra. 8/23", "5", "energiteca05@coexito.com", 7);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Coexito Cra. 1/18", "41", "energiteca41@coexito.com.co", 7);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Granada", "J1", "energitecaJ1@coexito.com.co", 7);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Cto. CCial Carrera", "N8", "energitecaN8@coexito.com.co", 7);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Cra. 1/45A", "03", "energiteca03@coexito.com.co", 7);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("La Flora", "45", "energiteca45@coexito.com.co", 7);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Arroyohondo", "N6", "energitecaN6@coexito.com.co", 29);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Tulua", "44", "energiteca44@coexito.com.co", 24);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Las Palmas", "N5", "energitecaN5@coexito.com.co", 18);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Versalles", "48", "energiteca48@coexito.com.co", 18);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Teusaquillo", "20", "energiteca20@coexito.com.co", 4);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Paloquemao", "25", "energiteca25@coexito.com.co", 4);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Centro Comercial Carrera", "27", "energiteca27@coexito.com.co", 4);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("7 de Agosto", "56", "energiteca56@coexito.com.co", 4);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Ave. 15/107", "57", "energiteca57@coexito.com.co", 4);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Avenida Chile", "L8", "energitecaL8@coexito.com.co", 4);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Normandia", "N3", "energitecaN3@coexito.com.co", 4);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Pepe Sierra", "N4", "energiteca@coexito.com.co", 4);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Fontibon", "Z8", "energitecaZ8@coexito.com.co", 4);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Chia", "Z7", "energitecaZ7@coexito.com.co", 4);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Tunja", "N9", "energitecaN9@coexito.com.co", 25);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Duitama", "P4", "energitecaP4@coexito.com.co", 11);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Santa Librada", "4", "energiteca4@coexito.com.co", 7);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Cra. 15/18", "19", "energiteca19@coexito.com.co", 7);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Tequendama", "J7", "energitecaJ7@coexito.com.co", 7);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Ave. Roosevelt", "L5", "energitecaL5@coexito.com.co", 7);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Camionera", "P8", "energitecaP8@coexito.com.co", 7);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Cañas Gordas", "Z1", "energitecaZ1@coexito.com.co", 7);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Buenaventura", "29", "energiteca29@coexito.com.co", 6);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Popayan", "30", "energiteca30@coexito.com.co", 21);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("La Glorieta", "Z6", "energitecaZ6@coexito.com.co", 21);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Ave. Boyaca/14", "85", "energiteca85@coexito.com.co", 19);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Calle 18", "L6", "energitecaL6@coexito.com.co", 19);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Seminario", "70", "energiteca70@coexito.com.co", 3);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Estadio", "72", "energiteca72@coexito.com.co", 3);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("20 de Julio", "L3", "energitecaL3@coexito.com.co", 3);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Murillo", "76", "energiteca76@coexito.com.co", 3);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Circunvalar", "Z9", "energitecaZ9@coexito.com.co", 3);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Santa Marta", "74", "energiteca74@coexito.com.co", 30);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Cartagena", "77", "energiteca77@coexito.com.co", 8);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Centro", "79", "energiteca79@coexito.com.co", 17);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Sincelejo", "87", "energiteca87@coexito.com.co", 23);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Valledupar", "88", "energiteca88@coexito.com.co", 26);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Santana", "Z3", "energitecaZ3@coexito.com.co", 26);
INSERT INTO branch (branchName, branchIdentifier, branchEmail, idCity) VALUES ("Rioacha", "L1", "energitecaL1@coexito.com.co", 22);
