INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("ALFA ROMEO", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("AUDI", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("AUSTIN", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("BMW", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("BUICK", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("BYD", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("CADILLAC", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("CHANA", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("CHERY", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("CHEVROLET", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("CITROEN", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("DACIA", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("DAEWOO", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("DAIHATSU", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("DFM", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("DODGE", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("FAW", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("FIAT", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("FORD", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("GEELY", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("HAFEI", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("HONDA", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("HYUNDAI", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("JAC", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("KIA", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("LADA", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("LANCIA", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("MAZDA", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("MERCEDES BENZ", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("MERCURY", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("MG", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("MITSUBISHI", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("NISSAN", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("OLTCIT", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("OPEL", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("PEUGEOT", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("PLYMOUTH", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("POLONEZ", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("PONTIAC", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("PORSCHE", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("RENAULT", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("SAAB", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("SEAT", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("SKODA", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("SUBARU", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("SUZUKI", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("TATA", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("TAVRIA", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("TOYOTA", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("VOLKSWAGEN", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("VOLVO", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("JAGUAR", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("LIFAN", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("MORRIS GARAGES", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("GREAT WALL", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("MINI COOPER", 1);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("ASIA MOTORS", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("BEIJING", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("CHANA", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("CHANGFENG", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("CHERY", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("CHEVROLET", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("CHRYSLER", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("CITROEN", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("DACIA", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("DAIHATSU", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("DFM", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("DFSK", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("DODGE", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("FORD", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("FOTON", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("HAFEI", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("HONDA", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("HUMMER", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("HYUNDAI", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("ISUZU", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("JEEP", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("KIA", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("LADA", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("LAND ROVER", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("MAHINDRA", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("MAZDA", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("MERCEDES BENZ", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("MITSUBISHI", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("NISSAN", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("RENAULT", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("SAIC", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("SSANG YONG", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("SUBARU", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("SUZUKI", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("TOYOTA", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("UAZ", 2);
INSERT INTO vehicleBrand(vehicleBrandName, idVehicle) VALUES ("VOLKSWAGEN", 2);
